# Generated by Django 3.0.6 on 2020-05-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('GenId', models.AutoField(primary_key=True, serialize=False)),
                ('GenNomb', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('PlatId', models.AutoField(primary_key=True, serialize=False)),
                ('PlatName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoId', models.AutoField(primary_key=True, serialize=False)),
                ('ProdName', models.CharField(max_length=50, verbose_name='Título')),
                ('ProdDesc', models.TextField(max_length=500, verbose_name='Descripción')),
                ('ProdClasi', models.TextField(choices=[('TODOS', 'TODOS'), ('TODOS+10', 'TODOS+10'), ('ADOLESCENTES', 'ADOLESCENTES'), ('MADURO+17', 'MADURO+17'), ('ADULTS+18', 'ADULTS+18'), ('SINCLASIFICAR', 'SINCLASIFICAR')], verbose_name='Clasificación ESRB')),
                ('ProdCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ProdImg', models.ImageField(null=True, upload_to='image/curso')),
                ('ProdPrev', models.BooleanField()),
                ('ProdEstado', models.BooleanField()),
                ('CatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Genero')),
                ('PlatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Plataforma')),
            ],
        ),
    ]
