# Generated by Django 3.1.1 on 2020-09-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('GenId', models.AutoField(primary_key=True, serialize=False)),
                ('GenNomb', models.CharField(max_length=50)),
                ('GenEsta', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['GenNomb'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('PlatId', models.AutoField(primary_key=True, serialize=False)),
                ('PlatName', models.CharField(max_length=50, verbose_name='Plataforma')),
                ('PlatEsta', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['PlatName'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ProductoId', models.AutoField(primary_key=True, serialize=False)),
                ('ProdName', models.CharField(max_length=50, verbose_name='Título')),
                ('ProdDesc', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('ProdCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('ProdStock', models.SmallIntegerField(default=0, verbose_name='Stock')),
                ('ProdMarca', models.CharField(default='', max_length=50, verbose_name='Marca')),
                ('ProdClasi', models.CharField(choices=[('TODAS LAS EDADES', 'TODOS'), ('MAYORES DE 10 AÑOS', 'TODOS+10'), ('MAYORES DE 13 AÑOS', 'ADOLESCENTES'), ('MAYORES DE 17 AÑOS', 'MATURE+17'), ('MAYORES DE 18 AÑOS', 'MATURE+18'), ('SIN CLASIFICAR', 'SIN CLASIFICAR')], max_length=20, verbose_name='Clasificación ESRB')),
                ('ProdImg', models.ImageField(null=True, upload_to='image/curso', verbose_name='Imagen')),
                ('ProdPrev', models.BooleanField(default=False, verbose_name='Preventa')),
                ('ProdEstado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ProdFechaLan', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('PreFinalPrev', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final preventa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('GenId', models.ManyToManyField(to='App.Genero', verbose_name='Género')),
                ('PlatId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.plataforma', verbose_name='Plataforma')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
    ]
