# Generated by Django 3.0.6 on 2020-05-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200531_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='CatId',
        ),
        migrations.AddField(
            model_name='genero',
            name='GenEsta',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='PlatEsta',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='GenId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='GenNomb',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='PlatName',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='PlatId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Plataforma', verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdEstado',
            field=models.BooleanField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdImg',
            field=models.ImageField(null=True, upload_to='image/curso', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdPrev',
            field=models.BooleanField(verbose_name='Preventa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdStock',
            field=models.SmallIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
