# Generated by Django 3.0.6 on 2020-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200531_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='GenId',
        ),
        migrations.AddField(
            model_name='producto',
            name='GenId',
            field=models.ManyToManyField(to='App.Genero', verbose_name='Géneros'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='PlatId',
        ),
        migrations.AddField(
            model_name='producto',
            name='PlatId',
            field=models.ManyToManyField(to='App.Plataforma', verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdEstado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdPrev',
            field=models.BooleanField(default=False, verbose_name='Preventa'),
        ),
    ]
