# Generated by Django 3.0.6 on 2020-05-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200531_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='GenEsta',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='GenNomb',
            field=models.CharField(max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='PlatEsta',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='PlatName',
            field=models.CharField(max_length=50, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdClasi',
            field=models.TextField(choices=[('TODOS', 'TODOS'), ('TODOS+10', 'TODOS +10'), ('ADOLESCENTES', 'ADOLESCENTES'), ('MADURO+17', 'MADURO +17'), ('ADULTS+18', 'ADULTS +18'), ('SINCLASIFICAR', 'SIN CLASIFICAR')], verbose_name='Clasificación ESRB'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
