# Generated by Django 3.0.6 on 2020-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200531_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProdClasi',
            field=models.CharField(choices=[('TODOS', 'TODOS'), ('TODOS+10', 'TODOS +10'), ('ADOLESCENTES', 'ADOLESCENTES'), ('MADURO+17', 'MADURO +17'), ('ADULTS+18', 'ADULTS +18'), ('SINCLASIFICAR', 'SIN CLASIFICAR')], max_length=20, verbose_name='Clasificación ESRB'),
        ),
    ]
