# Generated by Django 3.0.6 on 2020-06-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200531_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProdEstado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
