# Generated by Django 3.0.6 on 2020-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200603_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProdClasi',
            field=models.CharField(choices=[('TODAS LAS EDADES', 'TODOS'), ('MAYORES DE 10 AÑOS', 'TODOS+10'), ('MAYORES DE 13 AÑOS', 'ADOLESCENTES'), ('MAYORES DE 17 AÑOS', 'MATURE+17'), ('MAYORES DE 18 AÑOS', 'MATURE+18'), ('SIN CLASIFICAR', 'SIN CLASIFICAR')], max_length=20, verbose_name='Clasificación ESRB'),
        ),
    ]
