# Generated by Django 3.0.6 on 2020-06-04 03:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200603_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['created'], 'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='PlatId',
        ),
        migrations.AddField(
            model_name='producto',
            name='PlatId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.Plataforma', verbose_name='Plataforma'),
        ),
    ]
