# Generated by Django 3.0.6 on 2020-06-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200603_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ProdMarca',
            field=models.CharField(default='', max_length=50, verbose_name='Marca'),
        ),
    ]
