# Generated by Django 3.0.6 on 2020-06-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_producto_prodmarca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['GenNomb'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='plataforma',
            options={'ordering': ['PlatName'], 'verbose_name': 'Plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
    ]
