# Generated by Django 3.0.6 on 2020-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200605_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProdCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
    ]
