# Generated by Django 3.0.6 on 2020-06-05 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20200605_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='PlatId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Plataforma', verbose_name='Plataforma'),
        ),
    ]
