# Generated by Django 3.0.6 on 2020-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200605_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='GenId',
            field=models.ManyToManyField(to='App.Genero'),
        ),
    ]
