# Generated by Django 3.0.6 on 2020-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200605_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'get_latest_by': 'created', 'ordering': ['created'], 'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='GenNomb',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='GenId',
            field=models.ManyToManyField(to='App.Genero', verbose_name='Género'),
        ),
    ]
