# Generated by Django 3.1.1 on 2020-09-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200606_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ProdFechaLan',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProdDesc',
            field=models.TextField(max_length=1000, verbose_name='Descripción'),
        ),
    ]
