# Generated by Django 3.1.1 on 2020-09-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200921_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PreFinalPrev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final preventa'),
        ),
    ]
