# Generated by Django 3.1.1 on 2020-09-25 00:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='distrito',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='provincia', on_delete=django.db.models.deletion.CASCADE, to='cliente.distrito'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='provincia',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='departamento', on_delete=django.db.models.deletion.CASCADE, to='cliente.provincia'),
        ),
    ]
